//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientScheduler.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientScheduler.Service.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast.
        /// </summary>
        internal static string Breast {
            get {
                return ResourceManager.GetString("Breast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        internal static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flu.
        /// </summary>
        internal static string Flu {
            get {
                return ResourceManager.GetString("Flu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralPractitioner.
        /// </summary>
        internal static string GeneralPractitioner {
            get {
                return ResourceManager.GetString("GeneralPractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head&amp;Neck.
        /// </summary>
        internal static string HeadNeck {
            get {
                return ResourceManager.GetString("HeadNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oncologist.
        /// </summary>
        internal static string Oncologist {
            get {
                return ResourceManager.GetString("Oncologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
    }
}
